### ISSUE TITLE
Could you make a license Change to MIT or Apache 2.0

### ISSUE THREAD

**Issue by RonnyWeiss** [patrickmonaco/resource_diagram_plugin#1]
Hello

Could you please make a license Change to MIT or Apache 2.0? Because GPL 2.0 is often a license that makes such a software "useless" for most cases!

Kind regards

Ronny

**Comment by patrickmonaco** [comment]
Hi Ronny,
Ok, I'm going to change it.
Kind regards,
Patrick
Patrick Monaco

Envoyé depuis Yahoo Mail pour Android 
 
  Le jeu., mars 14, 2019 à 9:40, Ronny Weiss<notifications@github.com> a écrit :   
Hello

Could you please make a license Change to MIT or Apache 2.0? Because GPL 2.0 is often a license that makes such a software "useless" for most cases!

Kind regards

Ronny

**Comment by RonnyWeiss** [comment]
Hello Patrick

Thank you for quick answer and for change the license!

Kind regards

Ronny

**Comment by RonnyWeiss** [comment]
Hello Patrick

Maybe after change license you want to join the APEX Competition 2019 and win maybe 850€

https://apex.oracle.com/pls/apex/f?p=APEXPLUGINCOMPETITION19:DE

Kind regards

Ronny
